// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZRVTVQF0Hj6Bj7Loo3_mu82h69oh39V0',
    appId: '1:646922758747:web:7067fd438aeab1daf46d7e',
    messagingSenderId: '646922758747',
    projectId: 'marvel-comic-2e86e',
    authDomain: 'marvel-comic-2e86e.firebaseapp.com',
    storageBucket: 'marvel-comic-2e86e.firebasestorage.app',
    measurementId: 'G-FQZ8Z0DZ0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb6W25qgj0IEtSePoFJE3AdfXTQVTnLqs',
    appId: '1:646922758747:android:b7813312a8eef2b6f46d7e',
    messagingSenderId: '646922758747',
    projectId: 'marvel-comic-2e86e',
    storageBucket: 'marvel-comic-2e86e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnEiyq0VxVZ_bLYWOEjttuLOHSVJsTCBk',
    appId: '1:646922758747:ios:3bda6beda8541b4cf46d7e',
    messagingSenderId: '646922758747',
    projectId: 'marvel-comic-2e86e',
    storageBucket: 'marvel-comic-2e86e.firebasestorage.app',
    iosBundleId: 'com.example.marvelComicApp',
  );

}